src/waterfall.cpp

From: http://lists.qt-project.org/pipermail/interest/2015-October/019264.html
> Converting that to a QPixmap will entail a QImage::convertToFormat() to map the image into a system specific pixel format, usually QImage::RGB32 or
> QImage::ARGB32_Premultiplied, but any given QPA backend may override that with an other format if that is more compatible with its raster backingstore.
This approach reduce CPU usage in 27%

Waterfall: Use NoFormatConversion with fromImage

---

qml/DisplaySettings.qml
qml/InfoPage.qml
qml/MainMenu.qml
qml/MainPage.qml
qml/PingComboBox.qml
resources.qrc
src/logger.cpp
src/logger.h
src/main.cpp
src/settingsmanager.cpp
src/settingsmanager.h
src/settingsmanagerhelper.h

Fix #205 
Will help #199 
Fix #42

Settings manager: Create a class to manage all shared settings

---

.appveyor.yml

- Qt 5.11.0 does not exist anymore, update to Qt 5.11

appveyor: Update Qt version

---

src/loglistmodel.cpp
src/loglistmodel.h

- Move const variables that belong to model struct to private variables.
- They are defined only once
- They define how the entire model will work, makes more sense to move it to header

LogListModel corrections

---

src/sensor/ping.cpp
src/sensor/ping.h
src/sensor/sensor.h

- Needs https://github.com/bluerobotics/ping-protocol-cpp/pull/49
- Fix #212 
- Moves Ping and not Sensor to be visible for qml

Use Ping and not Sensor in QML, fix #212

---

qml/PingFileDialog.qml

We are building the binaries with Qt 5.11
fix #373 

pingfiledialog: Move from QtQuick 2.12 to 2.11

---

tools/compile.sh

Fix #396
Last version of linuxdeployqt adds commit hash name in the name of the file
Such thing creates a huge number of files in S3

compile: Correct AppImage deploy name

---

src/sensor/ping.cpp
src/sensor/ping.h
src/sensor/sensor.cpp
src/sensor/sensor.h
src/sensor/sensorarbitrary.h
src/waterfall/waterfall.cpp

Use `TODO:` and not `todo`, `todo,` or any variation

Improve todo notation

---

pingviewer.pro
src/network/networktool.cpp

fix #442 
This will show only commits with tags that do not contain 'continuous' or 'stable' in the name.

project: use git tag instead of git describe in order to find all

---

src/sensor/ping.cpp

All messages after handle will have a valid checksum
Helps #438 

ping: Remove checksum debug message

---

src/sensor/ping.h

In some messages (1212, 1300) confidence is uint16_t and in others (1211) is uint8_t

ping: Fix confidence type

---

tools/compile.sh

Travis result in timeout if there is no output in 10min
LinuxDeployQt takes more than 10min to do the package sometimes
Fix [#486](https://github.com/bluerobotics/ping-viewer/issues/486)

tools: Add periodic print of '.' to avoid travis timeout issue

---

qml/ConnectionMenu.qml

ConnectionMenu: Uses 115200 as default baudrate option

---

qml/ConnectionMenu.qml
qml/MainMenu.qml
qml/PingTextField.qml

TextField with validators does not emit onAccept or onEditingFinished when wrong inputs are in the TextField. We need to check if the focus was lost and the input is valid manually.
onEditingFinished is only emitted when TextField has focus, otherwise will not emit. That's why I'm moving to on Accept, this one will be emitted if the application loses focus or enter is emitted. 
Input variable from onEditingFinished was removed to use old/classic implementation of text variable after fixing logic problems with new implementation.

Fix wrong input when input loses focus

---

src/sensor/ping.cpp

~~general_request fail with id 1214.~~
It's working fine with 3.26
https://github.com/bluerobotics/ping-protocol/pull/113 need to be merged first.

Use general request

---

.travis.yml
docs/application-information.md
docs/connection-settings.md
docs/css/center_images.css
docs/device-settings.md
docs/display-settings.md
docs/faq-and-troubleshooting.md
docs/firmware-update.md
docs/index.md
docs/notifications-and-updates.md
docs/replay-data.md
mkdocs.yml

This adds a css rule to center all images in text, and replaces the html img tags with markdown where possible

Replace html images with markdown

---

src/sensor/ping.cpp

The sensor in the actual version fail to provide profile messages with general_request
This is related to [#492](https://github.com/bluerobotics/ping-viewer/issues/492)
This reverts commit 00f13e9170979dacdf251457526d2a788b60fa9b.

Revert "ping: Move from empty message to general_request"

---

src/link/udplink.cpp
src/sensor/protocoldetector.cpp
src/sensor/protocoldetector.h

@Williangalvani 	Please test with my remote raspberry.
This functions follows IBM documentation about socket connections for clients
https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_71/rzab6/howdosockets.htm
https://www.ibm.com/support/knowledgecenter/en/SSB23S_1.1.0.14/gtpc1/gtpc1mst104.html
1. create socket
2. bind (optional, but necessary for QUdpSocket::ReuseAddressHint)
3. read/write
4. close
Without `ReuseAddressHint`, the next connection request will fail if there were connections open.
Since this uses the `connectToHost` method, all read and write functions should use the `QIODevice` primitive.

Fix UDP usage with socat 

---

qml/Ping360ControlPanel.qml
src/sensor/ping360.h

The `round()` in the control panel is cosmetic only, to avoid broken (although real) numbers.
The math for range calculation generates numbers such as 22.98.
The float->int cast calculating `_sample_period` seemed to be falling shot of our range, so we can round up instead.
fix #572

Fix off by one

---

qml/PingSlider.qml

Also, right now all inputs are defined in integer steps. 

PingSlider: Value precision should not be defined by slider

---

src/sensor/protocoldetector.cpp

protocoldetector: Do not waitForDisconnected if socket is in UnconnectedState

---

qml/PingSlider.qml

PingSlider: Use single steps by default

---

src/link/seriallink.cpp

Fix error message if the port is already open
Also allows the connection to be redone if baud rate changes occur

seriallink: Check if port is open before opening

---

src/devicemanager/devicemanager.cpp

Fix [#577](https://github.com/bluerobotics/ping-viewer/issues/577)

devicemanager: Do not wait for thread to finish

---

src/waterfall/waterfall.cpp

The int constructor is faster on the initialization, found by
clazy

waterfall: dont use qcolor string constructor

---

src/link/abstractlink.cpp
src/link/abstractlink.h

Operator equals in a class that's supposed to be abstract is a code
smell, usually you want to copy the combination of the super class and
child class.
Code still compiles, that means that either the operator= is not used
or that the compiler implemented a correct operator=.

abstractlink: remove unused operator equals

---

qml/ConnectionMenu.qml
qml/DeviceManagerViewer.qml
src/link/udplink.cpp
src/link/udplink.h

This prevents invalid IP addresses and Ports. I had some crashes because of missing validation.
Also moves the Tooltip down closer to the device button, and fixes the transmit_duration unit.

Small fixes

---

.appveyor.yml

appveyor: Use always the last Qt version available of 5.12 from appveyor

---

qml/ConnectionMenu.qml
qml/Ping360ControlPanel.qml
qml/Ping360Status.qml
qml/PingStatus.qml
src/devicemanager/devicemanager.cpp
src/link/abstractlink.h
src/link/linkconfiguration.cpp
src/link/linkconfiguration.h
src/link/seriallink.cpp
src/link/seriallink.h
src/sensor/ping.cpp
src/sensor/ping360.cpp
src/sensor/ping360.h
src/sensor/protocoldetector.cpp

Replace https://github.com/bluerobotics/ping-viewer/pull/606
This PR replaces #606 using the automatic baud rate detection, also allows the user to select the best baud rate manually if necessary and to enable the automatic baud rate detection procedure again. 
1. Detects device via normal baud rates 
2. After user selection it checks for the possible baud rates and request N messages to make sure that everything is fine with this baud rate.
3. Select the desired baud rate and start profile requests
This also adds a check box and baud rate selection list for the user to select the desired baud rate. 
note: I'm using 5M and 3M to test not working baud rates

Ping360: Do automatic baud rate detection

---

src/sensor/ping360.h

The sensor 0 is in the back of the product, we should start the
scan from the product case `0 position`, that is the 200 of the sensor.

ping360: Fix initial angle for better visualization and better response time

---

src/settings/settingsmanagerhelper.h

Use .value only for unknown types. Currently we are only using
bool and int that triggered the warning. The fix is simple: a template
function will be swapped in compile time for the actuall call.

settingsmanagerhelper: dont call QVariant.value<bool> or <int>

---

qml/Chart.qml

Fix [#576](https://github.com/bluerobotics/ping-viewer/issues/576)
The OpenGL call miss some points in the final result of the draw

Chart: Remove useOpenGL call

---

src/link/seriallink.cpp
src/sensor/ping360.cpp
src/sensor/ping360.h
src/sensor/pingsensor.cpp
src/sensor/sensor.cpp

- Small improvements over #540 
- Corrections/Quality of life in ABR
I can break this in two PRs, but it's easier to test the speed improvements with the ABR improvements. 
This PR should hit something near 60~50Hz with the timer latency configured.
Linux: `sudo echo 1 > /sys/bus/usb-serial/devices/ttyUSB0/latency_timer`
Windows: **Device Manager** → Com port → **Properties** → **Advanced** → Latency Timer: 1
It takes 8s  to do a full spin in a 2m range and 2M baud rate.
> Note: Message frequency is not the same thing as full scan time. Messages in the same position will be faster and with more messages but with slow scan time. We should add scan time in the sensor status.

Improved speed: Updates over #540

---

qml/DeviceManagerViewer.qml

Fix [#609](https://github.com/bluerobotics/ping-viewer/issues/609)
The color appears weird in the gif..
But here is ok:

DeviceManagerViewer: Use background color in place of tooltip for user feedback

---

src/sensor/protocoldetector.cpp

Validated by Brian: `The Bluetooth test found the ping360 in 0:07`

protocoldetector: Add timeout in wait for bytes

---

src/waterfall/polarplot.cpp

The distance value was multiplied by 1e-3 unnecessary

Fix mouse range in polarplot

---

qml/PolarGrid.qml

This allow a better visualization of the values
Fix #703 
Old:
New:

PolarGrid: Change axis test to bold

---

src/sensor/ping360.cpp

This was done wrong, the multiplication was done in the `sample_period` it should be applied in pulse length.
This reverts commit 520ea4edac5fd4a720f48f9777785a067f331d78.

Revert "ping360: Change scalar from 2 to 4 in sample period calculation"

---

src/sensor/ping360.h

ping360: Remove reverse_direction when back to full scan

---

src/waterfall/polarplot.cpp
src/waterfall/polarplot.h

This allows a better visualization of the plot and the head indicator
Fix #703

polarplot: Add background color compatible with theme

---

src/sensor/ping360.h

Duplicate pulse duration as requested to improve visualization
It would be nice if someone could test that in the water 
Fix #702 

ping360: Improve pulse duration equation

---

qml/PingStatus.qml

Avoid unnecessary CPU usage and realocation of each new signal for each property
Fix #750

PingStatus: Disable models if parent is not visible

---

src/sensor/ping360.cpp
src/sensor/ping360.h

Use the angular speed plus the network delay to calculate the next probable timeout
Go back to the 4.2s WCS timeout after a 30s communication loss
Fix #747 

ping360: Improve timeout logic

---

qml/PingSlider.qml

helps #667 
medium is not anymore outside the area:
old:
new:

PingSlider: Update label size for text models

---

qml/PingSlider.qml

Theres a bud in qml that's activating some controls even when they
are not visible in the scene

pingslider: dont enable controls when not visible

---

src/sensor/ping360ethernetfinder.cpp

Broadcasting to 255.255.255.255 finds only responses from the default network interface (usually your router). With this patch we find it on the default interface + 192.168.2.x in case there are two network interfaces.

Find ping360 on secondary network

---

src/settings/qjsonsettings.cpp
src/settings/qjsonsettings.h

qjsonsettings: Add missing const in parameter

---

src/sensor/ping.cpp
src/sensor/ping.h
src/sensor/pingsensor.cpp
src/sensor/pingsensor.h

Encapsulate common ping variables inside a struct, this helps to understand what is sensor variables and what is not

Fix todos:  encapsulate ping common variables

---

src/link/abstractlink.cpp
src/link/abstractlink.h
src/link/filelink.cpp
src/link/link.cpp
src/link/seriallink.cpp
src/link/simulationlink.cpp
src/link/tcplink.cpp
src/link/udplink.cpp
src/main.cpp

We are helping ourselves forcing the name of the link in the constructor of an AbstractLink,
making it easier to provide the user the connection type that he's using. 
Fix #808

Force name in AbstractLink constructor 

---

qml/Chart.qml
src/util/util.cpp

I did a quick text with 1k points, as you can check here the resolution matchs:
My display has 1080 pixels.
Fix #732

Improve chart resolution

---

src/sensor/ping360.cpp
src/sensor/ping360.h

This commit adds a tracking interface for the sensor settings,
making it possible to invalidate incoming messages and force the new
settings.
Fix #781

ping360: Fix reset feature

---

src/devicemanager/devicemanager.cpp
src/devicemanager/devicemanager.h

This argument is not const for the QML frontend

devicemanager: Remove const from argument

---

src/link/logsensorstruct.cpp

Both QSysInfo::productVersion() and QSysInfo::prettyProductName()
are static

logsensorstruct: Both functions are already static

---

src/network/networkmanager.cpp

There is no smart pointer for an autodeleter pointer

networkmanager: Add a clear comment about downloadManager nature

---

src/sensor/ping360.h

The sensor offset is a sensor property since is a physical property and can change
between models.
The offset can also be a variable when receiving heading data from the sonar.

ping360: The offset should be in the sensor class

---

src/sensor/ping360.h

This makes more sense since the PROPERTY is double and the range() return is also double

ping360: Use double as argument

---

qml/PingStatus.qml
src/sensor/pingsensor.h

errMsg is not clear, since the message is from the nack message. 
This PR moves from errMsg to nack_message

Use correct name for property

---

src/settings/settingsmanager.cpp

We should support settings around the application upgrades

settingsmanager: Remove deprecated todo

---

src/sensor/ping.cpp

This approach will fix interface hiccups while flashing
avoiding the sleep of the main thread

ping: Move from QThread::msleep to QTimer::singleShot

---

src/settings/settingsmanagerhelper.h

settingsmanagerhelper: Move from deprecated qVariantFromValue to static QVariant::fromValue

---

src/link/linkconfiguration.cpp

linkconfiguration: Variables that are not connection specific should be ignored in tests

---

src/sensor/ping360.cpp

This is now done by `_sensorSettings`

ping360: Remove deprecated TODO

---

qml/opengl/polarplot/fragment.glsl

Some backends does not provide a default precision for fragment shaders.
Fix #888

opengl: polarplot: Add missing float precision

---

qml/opengl/polarplot/fragment.glsl

inspired by https://github.com/pxscene/pxCore/pull/690
fix #888

opengl: set precision only for GL_ES

---

docs/firmware-update.md

There is no need to do a device recovery if the LED is blinking 
It's probably a hardware problem

firmware-update: Improve the instructions if the LED is blinking

---

qml/Ping360Visualizer.qml

Ping360 head down configuration is not working in our current release, this fix the rotation logic with two rotation items 

Ping360Visualizer: Fix head down configuration

---

qml/DisplaySettings.qml
src/link/filelink.cpp
src/link/processlog.cpp
src/link/processlog.h
src/settings/settingsmanager.h

Some people may turn on the sonar, connect with ping-viewer, but without request or starting the scanning with it, or stopping and starting ping requests, for the user to not wait this unnecessary amount of time when playing the log, it was added an option where the user will have the log processed with a maximum timeout of each message of 100ms. So, if any interval between each message is bigger than 100ms, the interface will not wait for the entire time and process the message inside the 100ms interval.

Add option to run log with or without realtime update

---

src/waterfall/waterfall.cpp

Goes forward Qt 6 support using newer C++ features over legacy Qt functions
Fix #899 

waterfall: Use std::cbegin and std::cend over function call

---

qml/PingLogger.qml

qml: PingLogger: Fix bind with Qt 5.15 where delegates can't use parent

---

qml/Ping360ControlPanel.qml

We loose bind when we change the value in multiple places, to avoid such issue we use the Binding element to do that for us.
Helps #958

Ping360ControlPanel: Add Binding to ping.range to allow reset of the ui interface

---

qml/PingTextField.qml

The item should set the minimum size and not the size itself
Fix #975
Signed-off-by: Patrick Jo Pereira <patrickelectric@gmail.com>

PingTextField: Fix width and height

---

src/CMakeLists.txt

There are two problems here:
- Windows now by default it checks for tests if they are also no building
- Windows C++ Standard **refuses** to build with private definition 
Signed-off-by: Patrick Jo Pereira <patrickelectric@gmail.com>

src: Disable test for windows

---

src/sensor/ping.cpp

It's necessary to know the sensor configuration before changing it

sensor: ping: Request a single profile before using last configuration

---

docs/build-instructions.md

Ping-Viewer from now on will use cmake build system.
Fix #985

docs: build-instructions: Add cmake build instruction for Ping-Viewer v2.2.0+

---

docs/display-settings.md

- Fix #993
- add example of gradient colour with transparency
- show that custom gradient file doesn't need consistent colour formats across lines

docs: custom gradients minor update

---

qml/DeviceManagerViewer.qml
src/link/linkconfiguration.cpp
src/link/linkconfiguration.h
src/network/networkmanager.cpp
src/network/networkmanager.h

https://user-images.githubusercontent.com/1215497/133645785-f7c2b150-ec4d-4faa-87ba-88709a5fb4ee.mp4

Add require configuration on DeviceManager

---

cmake/git.cmake

The return was wrong since the GIT_* variables are never set if GIT_SUBMODULE is OFF

cmake: git: Add submodule update inside if check

---

.github/workflows/build.yml

Fixes #1018
In summary:
- This application requires the: VCRUNTIME140.dll, VCRUNTIME140_1.dll, MSVCP140.dll, and MSVCP140_1.dll;
- The ucrtbased.dll distribution is responsibility of Windows.
---
note: Marked as draft until artifact validation.

github: Change redistributed DLLs

---

src/link/filelink.cpp
src/link/filelink.h

Fix mac monterey

---

docs/firmware-update.md

Telling people to choose a firmware baudrate is no longer required with the 'auto' firmware, so is unnecessarily confusing.
Probably best to merge after https://github.com/bluerobotics/ping-arduino/pull/33.

docs: firmware-update: recommend latest version

---

README.md
docs/firmware-update.md

Updates:
- fix formatting issues
- update ping1d firmware specifier to latest version (3.28 -> 3.29)
- add separated instructions for original Ping Sonar vs new Ping2
- a button switcher might make more sense (especially once there's also Ping360 support), but I've kept it simple for now
- improve the README for people who want to build the docs
>**NOTE:** I've changed the Linux flashing command slightly, because I believe it was wrong before (using `.\` like Windows), but I haven't confirmed that the new form is actually correct

docs: improve firmware update instructions

---

.github/workflows/build.yml
.github/workflows/test.yml
tools/Dockerfile.pingviewer-linux-builder-ubuntu18
tools/aqt-settings.ini

Closes #1093 
Tested the build binary on:

Fix Linux deploy by using a Ubuntu 18 container
