.appveyor.yml, .travis.yml
=> ping-protocol-cpp: Update submodule

.travis.yml
=> travis: Use extra-plugins in linuxdeployqt

.appveyor.yml
Fix #104 
Signed-off-by: Patrick J.P <patrickelectric@gmail.com>
=> AppVeyor: Add openmp

qml/MainMenu.qml, qml/MainPage.qml, src/sensor/ping.cpp, src/sensor/ping.h, src/sensor/sensor.cpp
Waiting https://github.com/bluerobotics/ping-protocol-cpp/pull/29
=> Protocol update

.travis.yml, pingviewer.pro, qml/MainPage.qml, src/filemanager.cpp, src/filemanager.h, src/logger.cpp, src/logger.h, src/main.cpp, src/sensor/ping.cpp, src/sensor/sensor.cpp, src/sensor/sensor.h, src/src.pri
Waiting #108 to merge.
Add:
- Screen capture of the app
- Add folder management system
- Update paths for logs to be saved
- Save app log 
- Minor corrections
=> Folder manager

.appveyor.yml
=> Appveyor: Do continuous and tag deployment

qml/MainPage.qml, src/main.cpp, src/sensor/ping.cpp, src/sensor/ping.h
Depends of bluerobotics/ping-protocol-cpp#33
=> Use ping1DNamespace

.travis.yml
Co-authored-by: Patrick José Pereira <patrickelectric@gmail.com>
Co-authored-by: Jacob Walser <jacob@bluerobotics.com>
=> travis: Add s3 deployment

.appveyor.yml
=> appveyor: Add s3 deployment

qml/MainMenu.qml, qml/PingStatus.qml, src/sensor/ping.cpp, src/sensor/ping.h
=> more ping interface implementations

qml/MainPage.qml, qml/Ping1DVisualizer.qml, qml/ValueReadout.qml, src/ringvector.h, src/waterfall.cpp, src/waterfall.h
This do some updates related to waterfall widget
=> Waterfall update

qml/ValueReadout.qml
=> ValueReadout: Check initial position and correct if necessary

qml/InfoPage.qml, qml/MainPage.qml, qml/PingImage.qml, qml/PingItem.qml, qml/main.qml
This is also a functionality test, showing how dynamic and fluid layouts can be done better with "fill" item types.
There is also a video in slack.
=> Use InfoPage in fill mode

.appveyor.yml, .travis.yml, pingviewer.pro
Update to 5.11 and use QtQuickCompiler
Fix #133
=> Update project to use Qt 5.11

.travis.yml
=> Travis: Create release and debug dmg

src/waterfallgradient.cpp
=> WaterfallGradient: Do not copy stops

src/waterfall.cpp
=> Waterfall: Do not convert image while drawing

src/waterfall.cpp, src/waterfall.h
=> Waterfall: Only trigger time when necessary

qml/PingItem.qml
=> PingItem: Turn animation off by default

src/waterfall.cpp
=> Waterfall: Update in 20Hz at max

qml/MainMenu.qml
=> MainMenu: Disable custom start/stop when using auto gain

.travis.yml, pingviewer.pro, tools/iosccachecc.sh, tools/iosccachecxx.sh
=> travis: Add ccache

src/util.cpp
=> Util: Update serial device list each time

qml/Ping1DVisualizer.qml
=> Ping1DVisualizer: Use only floats with float variables

qml/PingLogger.qml
=> PingLogger: Update logic

src/waterfall.cpp
=> Waterfall: Add initial value in maxDepthToDrawInPixels

qml/ValueReadout.qml
=> ValueReadout: Add text color from confidence value

qml/Chart.qml, qml/MainPage.qml, qml/Ping1DVisualizer.qml, src/util.cpp, src/util.h, src/waterfall.cpp, src/waterfall.h
Video: https://transfer.sh/UVKM6/out-19.ogv
=> Fix #129: Add waterfall dynamic initial position 

src/sensor/ping.cpp
=> ping: Change serial device order in stm32flash command line

qml/DisplaySettings.qml
=> DisplaySettings: Remove render options

qml/MainPage.qml
=> MainPage: Set initial frequency to 15Hz

qml/MainMenu.qml, qml/MainPage.qml, src/sensor/ping.cpp, src/sensor/ping.h
=> Speed of sound

src/sensor/sensor.cpp, src/sensor/sensor.h
This simplify the delete propriety and fix a bug while running multiple log files
=> sensor: Use QPointer

src/sensor/ping.cpp
=> ping: Do not request messages if link type does not support it

qml/PingStatus.qml, src/sensor/ping.cpp, src/sensor/ping.h
=> Update ping status

qml/DepthAxis.qml, qml/Ping1DVisualizer.qml, resources.qrc
=> Depth axis

.travis.yml
=> travis: Use Qt 5.11.1

src/main.cpp
=> main: Solve error in qmlRegisterSingletonType definition of FileManager

qml/MainPage.qml, src/sensor/ping.cpp
Fix #221
This needs https://github.com/bluerobotics/ping-protocol-cpp/pull/48.
=> Ping: Stop requests if link is not open

src/util.cpp, src/util.h
=> Util: Invokable arguments need to be fully-qualified

qml/PingStatus.qml, src/sensor/ping.cpp, src/sensor/ping.h
fix #225 
Needs https://github.com/bluerobotics/ping-protocol-cpp/pull/52
=> Add parser stats

src/sensor/ping.cpp
=> Ping: Update NACK message

.travis.yml
=> travis: Change from g++7 to gcc7

qml/MainMenu.qml
Probably this values are compatible since 3.13
=> MainMenu: Update possible gains

qml/DepthAxis.qml, qml/MainMenu.qml, qml/MainPage.qml, qml/Ping1DVisualizer.qml, src/sensor/ping.cpp, src/waterfall.cpp, src/waterfall.h
=> Waterfall corrections

qml/DisplaySettings.qml, qml/FirmwareUpdate.qml, qml/MainMenu.qml, src/sensor/ping.cpp, src/sensor/ping.h
=> Add more debug functions

qml/MainMenu.qml, qml/MainPage.qml, src/main.cpp, src/sensor/ping.cpp, src/sensor/ping.h, src/sensor/sensor.cpp, src/sensor/sensor.h
- Add more high level link configuration level
- Allow connection manager app
- Decrease boilerplate code
- Needs https://github.com/bluerobotics/ping-protocol-cpp/pull/69
=> New connection configuration method

.travis.yml
=> travis: Add comments in CI script

src/sensor/ping.cpp
Fix #236 
Signed-off-by: Patrick J.P <patrickelectric@gmail.com>
=> ping: Call stm32flash with double quotes

qml/PingLogger.qml, src/settings/settingsmanager.h
=> pinglogger,settingsmanager: Add scrollLock settings

src/waterfall.cpp
=> More waterfall corrections and improvements 

src/filemanager.cpp, src/filemanager.h, src/logger.cpp, src/waterfall.cpp, src/waterfall.h, src/waterfallgradient.cpp, src/waterfallgradient.h
=> Add user waterfall gradients under Waterfall_Gradients folder

src/waterfall.cpp
=> waterfall: Add new gradients

src/waterfallgradient.cpp
Fix #282
Signed-off-by: Patrick J.P <patrickelectric@gmail.com>
=> waterfallgradient: Fix math operation under windows OS

src/waterfallgradient.cpp, src/waterfallgradient.h
=> Solve some small problems with user gradient

qml/imgs/createicon.sh, qml/imgs/svg2png.sh, tools/compile.sh, tools/iosccachecc.sh, tools/iosccachecxx.sh
=> Random shell scripts corrections

qml/MainPage.qml, src/filemanager.cpp, src/filemanager.h, src/logger.cpp, src/sensor/ping.cpp
Use Folder enum to get file and not fileTypeExtension.
- That's why Folder enum exist.
=> FileManager Updates

.appveyor.yml
=> appveyor: Do not push tags with branch name

.travis.yml, src/src.pri, src/test.cpp, src/test.h, src/waterfallgradient.cpp, tools/runtests.sh
Needs https://github.com/bluerobotics/ping-viewer/pull/287
=> Add first tests of the interface

src/detector.cpp, src/detector.h, src/filemanager.h, src/link/abstractlink.cpp, src/link/abstractlink.h, src/link/abstractlinknamespace.h, src/link/filelink.cpp, src/link/filelink.h, src/link/link.cpp, src/link/link.h, src/link/link.pri, src/link/linkconfiguration.cpp, src/link/linkconfiguration.h, src/link/logthread.cpp, src/link/logthread.h, src/link/pingsimulationlink.cpp, src/link/pingsimulationlink.h, src/link/seriallink.cpp, src/link/seriallink.h, src/link/simulationlink.cpp, src/link/simulationlink.h, src/link/tcplink.cpp, src/link/tcplink.h, src/link/udplink.cpp, src/link/udplink.h, src/sensor/ping.h, src/src.pri
Needs https://github.com/bluerobotics/ping-protocol-cpp/pull/79
=> move link files up from submodule

qml/Ping1DVisualizer.qml, src/sensor/ping.h
- Does not show weird values in release builds when not connected
- Does not show depthaxis when value is not set
=> Some small correction

pingviewer.pro
=> pingviewer: Force color output with ccache

qml/PingLogger.qml, src/detector.cpp, src/detector.h, src/link/filelink.cpp, src/link/linkconfiguration.cpp, src/link/linkconfiguration.h, src/link/seriallink.cpp, src/link/udplink.cpp, src/logger.cpp, src/sensor/ping.cpp, src/sensor/ping.h, src/sensor/sensor.cpp, src/sensor/sensor.h, src/settings/settingsmanager.h, src/settings/settingsmanagerhelper.h
- Fix #138 
- Correct `ProtocolDetector` implementation
- Correct `LinkConfiguration` debug operator
- Allow `SettingsManager` to work with structures and classes
- Update `LinkConfiguration` to work with `QDataStream`
- Random corrections
=> Update LinkConfiguration, Detector and other things

qml/MainMenu.qml, qml/MainPage.qml, src/sensor/ping.cpp, src/sensor/ping.h
=> Ping: Use continuous start

.travis.yml
=> travis: Fix qt version

qml/InfoPage.qml, qml/PingLogger.qml, src/logger/logger.cpp, src/logger/logger.h, src/logger/loglistmodel.cpp, src/logger/loglistmodel.h, src/settings/settingsmanager.h
- Log all categories by default
- Control visibility of each category
- Can see old messages of categories that visibility was off 
Needs #308
=> Control visibility of each category in logger widget

tools/compile.sh
=> compile: Add --with-clang option

src/main.cpp
=> main: Start logger ASAP

qml/FirmwareUpdate.qml, qml/MainPage.qml, qml/PingStatus.qml, src/link/pingsimulationlink.cpp, src/sensor/ping.cpp, src/sensor/ping.h, src/sensor/protocoldetector.cpp
update protocol fields and vector handling.
Needs https://github.com/bluerobotics/ping-protocol/pull/85
=> Dynamic protocol

qml/MainMenu.qml
=> MainMenu: Hide serial or UDP settings when necessary

src/filemanager/filemanager.h, src/logger/logger.h, src/logger/loglistmodel.h, src/network/networkmanager.h, src/network/networktool.h, src/notification/notificationmanager.h, src/sensor/ping.h, src/sensor/protocoldetector.h, src/sensor/sensor.h, src/sensor/sensorarbitrary.h, src/settings/qjsonsettings.h, src/settings/settingsmanager.h, src/style/stylemanager.h, src/util/util.cpp, src/util/util.h, src/waterfall/waterfall.h
=> Use Q_DISABLE_COPY when necessary 

src/link/linkconfiguration.cpp, src/link/linkconfiguration.h, src/sensor/ping.cpp, src/sensor/ping.h, src/sensor/protocoldetector.h
- This also allow any previous link configuration to be used by detector
=> Small corrections

src/main.cpp, src/network/networktool.cpp
=> Git repository regex to work with and without .git

src/sensor/protocoldetector.cpp
=> protocoldetector: Correct BlueROV UDP port for ping

src/sensor/ping.cpp
=> ping: Do not request or save configuration if running a replay

src/sensor/ping.cpp, src/sensor/ping.h
=> ping: Save last link configuration for manual input

src/logger/loglistmodel.cpp, src/logger/loglistmodel.h
=> loglistmodel: Fix #352

src/logger/logger.cpp, src/logger/logger.h
=> logger: move _colors to private and change normal text color

src/sensor/protocoldetector.cpp
=> protocol: submodule update

qml/InfoPage.qml, qml/MainMenu.qml, qml/icons/configure.svg, qml/icons/connect.svg, resources.qrc, src/sensor/ping.cpp, src/settings/settingsmanager.h, src/style/stylemanager.h
Follow this changes: https://github.com/bluerobotics/ping-viewer/pull/359#issuecomment-447079705
=> Update main configuration interface

qml/PingLogger.qml, src/logger/loglistmodel.cpp
=> Fix memory leak temporary

tools/compile.sh
This avoids the issue: https://github.com/probonopd/linuxdeployqt/issues/340
Helps #377 
=> compile: Fix linuxdeployqt

.appveyor.yml
=> appveyor: Add openssl dlls in deploy folder

LICENSE.md
=> License: First commit

qml/main.qml
=> main: Update title to be Ping Viewer - Tag - Hash

qml/ConnectionMenu.qml
=> ConnectionMenu: Remove sonar type

qml/ConnectionMenu.qml
=> ConnectionMenu: Shows simulation only in debug mode

src/sensor/ping.cpp, src/sensor/ping.h
=> ping: Check if stm32flash exist before bootloader and flash call

src/sensor/ping.cpp, src/sensor/ping.h
=> ping: Update sensor settings after firmware update

src/main.cpp, tools/compile.sh, tools/runtests.sh
=> Add runtime test

README.md
=> README: Add first version

qml/Ping1DVisualizer.qml, src/waterfall/waterfall.cpp, src/waterfall/waterfall.h
=> Ping1DVisualizer: Hide readout line when mouse not in chart area

pingviewer.pro, qml/main.qml
=> main: Remove hash with normal releases

qml/ConnectionMenu.qml, src/sensor/protocoldetector.cpp
=> Add 9600 baudrate

README.md
=> README: Add download section and icons

qml/DepthAxis.qml, qml/ValueReadout.qml
=> Add outline in texts that are over the waterfall

qml/MainMenu.qml
=> MainMenu: Limit max user ping frequency in 30 pps

tools/compile.sh
https://github.com/probonopd/linuxdeployqt/issues/284
=> compile: Make linuxdeployqt icon engine more complete

qml/Ping1DVisualizer.qml, qml/ValueReadout.qml
fix #441![image](https://user-images.githubusercontent.com/8315108/51888781-6eda9a80-2365-11e9-8cb5-4fdcba94f5b5.png)
=> Readout position

qml/InfoPage.qml
=> InfoPage: Fix reset icon

qml/MainMenu.qml, qml/PingTextField.qml
=> Correct PingTextField behavior 

src/link/seriallink.cpp, src/sensor/ping.cpp, src/sensor/protocoldetector.cpp, src/sensor/protocoldetector.h
=> Fix protocol detector scan call

qml/FirmwareUpdate.qml, qml/MainMenu.qml, qml/PingFileDialog.qml, src/flash/flash.pri, src/flash/flasher.cpp, src/flash/flasher.h, src/main.cpp, src/network/networkmanager.cpp, src/network/networkmanager.h, src/sensor/ping.cpp, src/sensor/ping.h, src/sensor/sensor.h, src/src.pri
=> Add auto flash feature

qml/ConnectionMenu.qml
=> ConnectionMenu: Fix usage of PingTextField

qml/PingStatus.qml, src/link/linkconfiguration.h
=> Improve PingStatus layout and add link configuration

qml/PingStatus.qml
=> PingStatus: Use repeat to deal with status text

src/sensor/protocoldetector.cpp
=> protocoldetector: Check for socket bound state before receiveDatagram

qml/Ping1DVisualizer.qml, qml/ValueReadout.qml
=> Fix readout position 

.travis.yml
It appears that travis_terminate is not working properly,
moving deployment call to if check
Fix #487
=> travis: Do not deploy PRs

qml/InfoPage.qml
=> InfoPage: Improve categories position

qml/FirmwareUpdate.qml, qml/MainMenu.qml, src/flash/flasher.cpp, src/flash/flasher.h, src/sensor/ping.cpp
=> Add flash feedback for the user

src/waterfall/waterfall.h, src/waterfall/waterfallgradient.h
=> waterfall: Add missing header guard

.travis.yml
Helps [#354](https://github.com/bluerobotics/ping-viewer/issues/354)
=> travis: Update linux builds to use Qt 5.12.2

src/link/abstractlink.cpp, src/link/filelink.cpp, src/link/linkconfiguration.h, src/link/seriallink.cpp, src/link/seriallink.h, src/link/tcplink.cpp, src/link/udplink.cpp
=> link: Fix finishConnection call

.appveyor.yml, pingviewer.pro, src/link/seriallink.cpp, src/logger/logger.cpp, src/logger/loglistmodel.cpp, src/logger/loglistmodel.h, src/main.cpp
**THIS PR NEEDS MODIFICATIONS AFTER ACCEPTING**
[auto crash feature to test PR and deployment]
This adds kcrash on windows deployment.
To test it, this binary will autocrash after some seconds and a window will appear:
=> KCrash support for windows

README.md
=> README: Add lgtm quality grade

qml/InfoPage.qml, src/util/util.cpp, src/util/util.h
=> Restart application after reset settings

.appveyor.yml, src/link/pingsimulationlink.cpp, src/main.cpp, src/sensor/ping.cpp, src/sensor/ping.h, src/sensor/protocoldetector.cpp, src/sensor/sensor.cpp, src/test.cpp
Needs: https://github.com/bluerobotics/ping-protocol/pull/132
This update ping-submodule to use master
Also allows device manager development
Needs Ping 3.27 firmware release.
^ https://github.com/bluerobotics/ping-firmware-private/releases/tag/3.27rc
=> [1] Start Ping360 support integration with new protocol structure

README.md
=> README: Add first commit

docs/connection-settings.md
=> connection-settings: Fix code block style

qml/Ping360Visualizer.qml, qml/PolarGrid.qml, resources.qrc, src/sensor/ping360.cpp, src/sensor/ping360.h, src/waterfall/polarplot.cpp, src/waterfall/polarplot.h
=> Improve polar draw interface with axis and corrections

qml/PolarGrid.qml
=> PolarGrid: Add angular grid

qml/Ping360Visualizer.qml, qml/PolarGrid.qml, src/waterfall/polarplot.cpp, src/waterfall/polarplot.h
=> Improve grids, axis range indicator, spinner and more

src/sensor/protocoldetector.cpp, src/sensor/protocoldetector.h
=> protocoldetector: Request DeviceInformation message from sensors

.gitmodules, lib/ping-cpp/ping-cpp.pri, pingviewer.pro, qml/MainPage.qml, qml/Ping1DControlPanel.qml, qml/Ping360ControlPanel.qml, src/link/ping1dsimulationlink.cpp, src/link/ping360simulationlink.cpp, src/link/simulationlink.h, src/main.cpp, src/sensor/parser-ping.cpp, src/sensor/parser-ping.h, src/sensor/parser.h, src/sensor/ping.cpp, src/sensor/ping.h, src/sensor/ping360.cpp, src/sensor/ping360.h, src/sensor/pingsensor.cpp, src/sensor/pingsensor.h, src/sensor/protocoldetector.cpp, src/sensor/protocoldetector.h, src/sensor/sensor.cpp, src/sensor/sensor.h, src/test.cpp, tools/testdoxygen.sh
Before merging this:
- merge ping-protocol pr: https://github.com/bluerobotics/ping-protocol/pull/156
- update ping-protocol submodule in ping-cpp and force push (so that we use a commit from ping-protocol master)
- update the ping-cpp submodule here (so that we use a commit from ping-cpp master)
=> Update submodule to ping-cpp

qml/ConnectionMenu.qml, qml/Ping360ControlPanel.qml, qml/Ping360Visualizer.qml, qml/PingComboBox.qml, qml/PolarGrid.qml, resources.qrc, src/devicemanager/devicemanager.cpp, src/link/linkconfiguration.cpp, src/link/linkconfiguration.h, src/link/ping360simulationlink.cpp, src/main.cpp, src/sensor/ping.h, src/sensor/ping360.cpp, src/sensor/ping360.h, src/sensor/protocoldetector.cpp, src/sensor/protocoldetector.h, src/waterfall/polarplot.cpp, src/waterfall/polarplot.h
Needs: https://github.com/bluerobotics/ping-cpp/pull/6
=> Final integration with Ping360

src/waterfall/polarplot.cpp
=> polarplot: Correct mouse distance and angle to be degrees and meters

qml/MainPage.qml, qml/Ping360Visualizer.qml, src/sensor/sensor.cpp, src/sensor/sensor.h
=> Update Visualizer function and clear plot in scale changes 

qml/DisplaySettings.qml
=> DisplaySettings: Fix sensorVisualizer display settings widget

qml/Ping360Visualizer.qml
=> Ping360Visualizer: Add vertical and horizontal flip

src/sensor/ping360.cpp
=> ping360: Fix QVector<double> initialization

pingviewer.pro, qml/Ping360ControlPanel.qml, qml/Ping360Visualizer.qml, qml/PolarGrid.qml, src/sensor/ping360.cpp, src/sensor/ping360.h
=> Add sector view

qml/Ping360ControlPanel.qml, qml/Ping360Status.qml, qml/Ping360Visualizer.qml, qml/PolarGrid.qml, src/sensor/ping360.cpp, src/sensor/ping360.h
=> Ping360 parameters

qml/Ping360ControlPanel.qml, qml/Ping360Visualizer.qml, qml/PingSlider.qml, resources.qrc, src/sensor/ping360.h
Update control panel to use sliders, fix some bugs. Needs #563 
Sliders require the least amount of user interaction to adjust each of these settings, and this is more mobile friendly (in case we support mobile in the future).
=> Ping360 control

src/sensor/ping360.cpp
Needs #565 
fix #553 
fix #554
=> Ping360 bugs

qml/PingSlider.qml
Wheel control allow precision inputs in sliders.
=> Enable wheel control

src/link/udplink.cpp
=> udplink: Remove unnecessary bind

qml/Ping360ControlPanel.qml, qml/Ping360Status.qml, src/sensor/ping360.cpp, src/sensor/ping360.h, src/sensor/pingsensor.h
fix #575 
fix #574 
fix #570 
fix #568
=> Ping360 dev

src/sensor/protocoldetector.cpp
=> protocoldetector: Break any existing loop if _activate is false

qml/Ping360ControlPanel.qml, qml/PingComboSlider.qml, qml/PingSlider.qml, resources.qrc
=> qml: Add new Qml entity: ComboSlider

qml/MainPage.qml, qml/Ping360ControlPanel.qml, qml/PingImage.qml, qml/PingItem.qml, qml/PingNotificationArea.qml
Fix [#596](https://github.com/bluerobotics/ping-viewer/issues/596)
=> Ping360ControlPanel: Add advanced settings button

qml/DisplaySettings.qml, qml/InfoPage.qml, qml/MainPage.qml, qml/PingItem.qml
=> Fix startup qml warnings 

qml/PingItem.qml
=> Fix NoControlPanel behavior when connecting 

qml/Ping1DControlPanel.qml, qml/Ping360ControlPanel.qml
This parents was setting height and width breaking our last version of PingItem.
Fix #623
=> Remove unused parents

qml/Ping360Status.qml, src/sensor/ping360.cpp, src/sensor/ping360.h
=> Add frequency information about profile messages 

src/waterfall/waterfall.h
mouseDepthChanged is declared in waterfall.h
=> waterfallplot: remove signal override

qml/Ping360ControlPanel.qml, qml/PingComboSlider.qml
Use PingControlSlider for the range selection
=> Range selection

qml/ConnectionMenu.qml, src/devicemanager/devicemanager.cpp, src/devicemanager/devicemanager.h, src/main.cpp
Fix #612
Needs: https://github.com/bluerobotics/ping-cpp/pull/8
=> Improve manual connection

src/devicemanager/devicemanager.cpp, src/devicemanager/devicemanager.h, src/sensor/ping360ethernetfinder.cpp, src/sensor/ping360ethernetfinder.h
=> DeviceManager: Enable detection of Ping360 over ethernet

src/sensor/ping360.cpp, src/sensor/protocoldetector.cpp
- We can't enable the flag since maddy fails to compile
future PRs for maddy are necessary
=> Fix shadow variables

src/style/stylemanager.h, src/util/pingproperties.cpp, src/util/pingproperties.h
Now we can start using it thru the code
=> pingproperties: move the properties macro elsewhere

qml/DeviceManagerViewer.qml
=> devicemanagerviewer: add a single line between delegates

qml/Ping360Status.qml, qml/PingStatus.qml
Make the Status panels movable in the ping1d and ping 360
=> Drag drop status

src/settings/settingsmanager.cpp, src/settings/settingsmanagerhelper.h
=> Fix reset settings 

src/sensor/ping360.h
=> ping360: max valid baudrate is 2Mbaud

src/sensor/ping360.h
Fix [#652](https://github.com/bluerobotics/ping-viewer/issues/652)
=> ping360: Fix message frequency filter to a fixed value of 3Hz

src/sensor/ping360.cpp
Fix #656 - Avoid unnecessary baud rate changes
Fix detectBaudrates position and count attribution.
=> ABR corrections

tools/runtests.sh
=> Improve CI script to fail earlier 

qml/ConnectionMenu.qml, qml/DisplaySettings.qml, qml/FirmwareUpdate.qml, qml/InfoPage.qml, qml/NoControlPanel.qml, qml/Ping1DControlPanel.qml, qml/Ping360ControlPanel.qml, qml/PingGroupBox.qml, qml/PingNotificationArea.qml, resources.qrc
Fix #582 
Fix a bug with the last versions of ping-viewer and the notification widget
I also adds a new element PingGroupBox to fix the label position 
> Note: The notification widget only fails with the deployed version of ping-viewer, you can download and test it from [here](https://github.com/bluerobotics/ping-viewer/releases/tag/continuous-test_notification).
=> Improve notification widget

pingviewer.pro, src/link/seriallink.cpp, src/link/seriallink.h
Helps #665 
For windows and linux
=> Configure serial latency for the lowest possible

qml/MainPage.qml, src/devicemanager/devicemanager.cpp, src/devicemanager/devicemanager.h, src/link/filelink.cpp, src/link/filelink.h, src/link/logsensorstruct.cpp, src/link/logsensorstruct.h, src/link/sensorinfo.cpp, src/link/sensorinfo.h, src/sensor/ping.cpp, src/sensor/ping360.cpp, src/sensor/pingsensor.cpp, src/sensor/pingsensor.h, src/sensor/sensor.cpp, src/sensor/sensor.h, tools/runtests.sh
=> Add new log file structure 

qml/MainPage.qml
=> MainPage: Check for visualizer before calling sensorVisualizer functions

src/link/filelink.cpp, src/link/link.cpp, src/link/seriallink.cpp, src/link/udplink.cpp, src/sensor/hexvalidator.cpp, src/sensor/ping.cpp, src/sensor/ping360.cpp, src/sensor/protocoldetector.cpp, src/sensor/sensor.cpp, src/sensor/sensor.h
=> Use missing PING_LOGGING_CATEGORY in some classes

qml/PolarGrid.qml, src/waterfall/polarplot.h
=> Fix distance truncated value in polar plot for ping360

qml/PingStatus.qml
=> PingStatus: Improve position logic

src/sensor/pingsensor.cpp, tools/compile.sh
=> Fix mac builds

docs/build-instructions.md, docs/developers-and-oems.md, docs/libraries-and-tools.md, mkdocs.yml
=> developers: Add build instructions and libraries and tools

src/link/processlog.cpp
=> Fix processlog crash

src/sensor/ping360.cpp, src/sensor/ping360.h
=> Improve sample period equation

qml/Ping360Visualizer.qml
=> Ping360Visualizer: Makes vertical and horizontal flip mutually exclusive for 360 sector

qml/PolarGrid.qml
=> PolarGrid: Improve round method

qml/Chart.qml, qml/Ping360Visualizer.qml
=> Flip A-Scan in ping360 and add the option in visualizer settings 

src/sensor/ping360.cpp, src/sensor/ping360.h
=> Fix debug window to show log playback information 

src/waterfall/polarplot.cpp, src/waterfall/polarplot.h
=> polarplot: Fix background mask to work with different sector sizes

qml/MainPage.qml, src/link/processlog.cpp
=> Organize processlog and fix multiple playbacks calls

src/link/logsensorstruct.cpp
=> logsensorstruct: Remove unused QSysInfo in source

qml/Ping360ControlPanel.qml
=> Ping360ControlPanel: Remove angle offset

qml/ConnectionMenu.qml, qml/DeviceManagerViewer.qml, src/devicemanager/devicemanager.cpp
=> Move simulation to manual connection

qml/Ping1DVisualizer.qml, qml/Ping360Visualizer.qml
=> Add option to remove ascan

qml/Ping1DVisualizer.qml, qml/Ping360Visualizer.qml, src/util/util.h
=> Remove default antialiasing when running under mac

qml/Ping360Visualizer.qml
=> Ping360Visualizer: Move from vertical and horizontal flip to Head down option

qml/FirmwareUpdate.qml, qml/MainPage.qml, qml/Ping1DControlPanel.qml, qml/Ping360ControlPanel.qml, src/link/linkconfiguration.h
=> Move flash to submenu

qml/Ping1DControlPanel.qml, qml/Ping360ControlPanel.qml, qml/PingImage.qml
=> Move from wrench to arrow for configuration menu

tools/compile.sh
compile: Add libc6 copyright for linuxdeployqt
=> Fix linuxdeployqt

src/flash/flasher.cpp
=> flasher: Search for stm32flash in OS before local path

qml/Ping360Visualizer.qml
=> Ping360Visualizer: Save flip AScan setting

qml/Ping1DVisualizer.qml, qml/Ping360Visualizer.qml
=> Fix combobox size with different contents 

qml/Ping1DControlPanel.qml, qml/Ping360ControlPanel.qml, src/sensor/ping.cpp, src/sensor/ping.h, src/sensor/ping360.cpp, src/sensor/ping360.h, src/sensor/sensor.cpp, src/sensor/sensor.h
=> Add reset settings button in ping1d and ping360 control panel

pingviewer.pro, qml/Ping360Visualizer.qml, src/sensor/ping360.cpp, src/sensor/ping360.h
It reduces 360º@2m scan speed from 7.7~7.8s down to 7s.
=> Improve scan time

src/link/ping360simulationlink.cpp
Fix problems with range related equations
=> Ping360Simulationlink: Add missing sample period

src/devicemanager/devicemanager.cpp, src/devicemanager/devicemanager.h, src/sensor/ping360ethernetfinder.cpp, src/sensor/ping360ethernetfinder.h, src/sensor/protocoldetector.cpp, src/sensor/protocoldetector.h
- ping360ethernetfinder: Use the correct update link function
- devicemanager: Deal with multiple detectors source 
Fix #777
=> Fix ping360ethernetfinder and devicemanager

qml/Ping360Visualizer.qml
=> Ping360Visualizer: Remove some unused variables

src/link/filelink.h
=> filelink: Add missing final override in setPackageIndex

src/notification/notificationmanager.cpp
=> notificationmanager: Remove unnecessary lambda

qml/ValueReadout.qml
=> Improve and fix ValueReadout behavior 

qml/PingLogger.qml
=> PingLogger: Add item selection for user to copy

src/logger/logger.h, src/test.cpp, src/test.h
=> Add logger test

.travis.yml
=> travis: Fix docs deployment

qml/FirmwareUpdate.qml, qml/MainPage.qml, qml/PingStatus.qml, tools/runtests.sh
=> Add test for runtime warning messages 

qml/PingStatus.qml, src/link/abstractlink.cpp, src/link/abstractlink.h
=> Add bitrate information about link

pingviewer.pro
=> pingviewer: Use fast compilation flags in release mode

src/util/util.cpp
=> util: Fix compare logic

src/link/linkconfiguration.h, src/link/ping1dsimulationlink.cpp, src/link/ping360simulationlink.cpp, src/link/simulationlink.h, src/settings/settingsmanager.cpp, src/settings/settingsmanager.h, src/settings/varianttree.cpp, src/settings/varianttree.h, src/util/util.cpp, src/util/util.h
- Move util function to static and fix shadow variable
- Add const reference for some parameters
- Remove unnecessary constructor 
- Use QRandomGenerator over qrand
=> Random fixes corrections around

qml/ValueReadout.qml
- Add test for margin and maxSize values
Fix #803 
Signed-off-by: Patrick Jo Pereira <patrickelectric@gmail.com>
=> ValueReadout: Check for each variable to avoid multiple calls

.travis.yml, src/devicemanager/devicemanager.cpp, src/filemanager/filemanager.cpp, src/logger/logger.cpp, src/network/networkmanager.cpp, src/network/networkmanager.h, src/network/networktool.cpp, src/notification/notificationmanager.cpp, src/sensor/protocoldetector.cpp, src/settings/settingsmanager.cpp, src/style/stylemanager.cpp, src/util/util.cpp, src/util/util.h
=> Fix singleton self call

src/devicemanager/devicemanager.cpp
=> devicemanager: Fix ownership of devicemanager

docs/display-settings.md
=> display-settings: Fix color string format

src/sensor/ping.cpp, src/sensor/ping360.cpp
It improves loop execution time around 30%
Fix #556
=> Improve for loop with pragma for

CMakeLists.txt, src/CMakeLists.txt, src/devicemanager/CMakeLists.txt, src/filemanager/CMakeLists.txt, src/filemanager/filemanager.cpp, src/flash/CMakeLists.txt, src/link/CMakeLists.txt, src/logger/CMakeLists.txt, src/network/CMakeLists.txt, src/notification/CMakeLists.txt, src/sensor/CMakeLists.txt, src/settings/CMakeLists.txt, src/style/CMakeLists.txt, src/util/CMakeLists.txt, src/waterfall/CMakeLists.txt, tools/runtests.sh
- Add cmake build system
- Add travis test 
Replace #680
Fix #549
=> Add CMake build system

src/link/abstractlink.h, src/link/linkconfiguration.h
=> abstractlink: Fix setConfiguration call

qml/Ping1DVisualizer.qml, qml/Ping360Visualizer.qml, src/main.cpp, src/waterfall/CMakeLists.txt, src/waterfall/gradientscale.cpp, src/waterfall/gradientscale.h, src/waterfall/waterfall.h, src/waterfall/waterfallgradient.cpp
=> Add gradient scale

src/devicemanager/devicemanager.cpp, src/logger/logger.h, src/sensor/ping.cpp, src/sensor/ping360.h, src/sensor/protocoldetector.cpp, src/settings/settingsmanager.cpp, src/settings/settingsmanager.h
=> Save user manual connections to be scanned 

src/sensor/ping.cpp, src/sensor/ping360.cpp, src/sensor/pingsensor.cpp
=> Add message name with id in debug messages

qml/Ping360Visualizer.qml, qml/opengl/polarplot/fragment.glsl, qml/opengl/polarplot/vertex.glsl, resources.qrc, src/waterfall/polarplot.cpp, src/waterfall/polarplot.h
Brigs the cpu usage down from 45% to 15% when running with ping360. 
Fix #425
=> Ping360: Use OpenGL to do the cartesian->polar transformation 

qml/DeviceManagerViewer.qml, qml/MainPage.qml, src/CMakeLists.txt, src/commandline/CMakeLists.txt, src/commandline/commandline.pri, src/commandline/commandlineparser.cpp, src/commandline/commandlineparser.h, src/devicemanager/devicemanager.cpp, src/devicemanager/devicemanager.h, src/link/linkconfiguration.cpp, src/link/linkconfiguration.h, src/link/ping360simulationlink.cpp, src/link/ping360simulationlink.h, src/link/simulationlink.h, src/main.cpp, src/src.pri, src/test.cpp, tools/compile.sh, tools/runtests.sh
- Add command line parser 
- Add writable ping360 simulation
- Add Ping360 profile request speed test
Fix #796
=> Add ping360 speed test and some new features 

qml/FirmwareUpdate.qml
=> FirmwareUpdate: Add Baudrate label

qml/PingSlider.qml
@jaxxzer Sorry, I forgot to push before merge. 
=> PingSlider: Add comments about onModelValueChanged

qml/Ping360ControlPanel.qml
=> Ping360ControlPanel: modelValue is already being set by `modelValue: ping.rage` bind

src/waterfall/polarplot.cpp
Ping360 will provide 666¹ when scanning with 1m range
1- _"let anyone with understanding calculate the number of the beast, for it is the number of a person. Its number is six hundred sixty-six."_
=> polarplot: Add scale variable when sensor provides less than 1200 points

.gitmodules, CMakeLists.txt, lib/fmt/fmt.pri, pingviewer.pro, src/CMakeLists.txt, src/logger/logger.cpp
=> Add terminal color output

qml/Ping360ControlPanel.qml
=> Ping360ControlPanel: Remove startAngle since it does not exist

qml/ConnectionMenu.qml, qml/Ping1DVisualizer.qml
=> Update Changed suffix from some missed binds from our last patch 

qml/opengl/polarplot/fragment.glsl
Fix @Williangalvani problem with radeon video board
=> opengl: polarplot: Fix sampleOffset assignment

src/link/linkconfiguration.cpp, src/sensor/sensor.h
=> sensor: Remove deprecated todo

src/sensor/ping360.cpp
=> ping360: Add printSensorInformation content

src/link/filelink.h
The log handle is done by ProcessLog class
=> filelink: Remove deprecated todo

qml/Ping1DStatusModel.qml, qml/Ping360StatusModel.qml, qml/PingStatus.qml, src/sensor/sensor.cpp
limit update rate from sensor properties to 5Hz
=> Fix model cpu usage

src/link/seriallink.cpp
=> serialink: Move from todo to issue

src/sensor/pingsensor.h
=> pingsensor: Remove deprecated todo

src/waterfall/waterfall.cpp
The available colors are here:
https://github.com/bluerobotics/ping-viewer/blob/d2cf58c5c836513bde210d42369a928943a55931/src/waterfall/waterfall.cpp#L13
=> waterfall: Thermal 5 does not exist anymore, move to Thermal blue

qml/Ping1DControlPanel.qml
=> Ping1DControlPanel: Remove bind with inexistent variable animationType

CMakeLists.txt, src/CMakeLists.txt, src/commandline/CMakeLists.txt, src/devicemanager/CMakeLists.txt, src/link/CMakeLists.txt, src/logger/CMakeLists.txt, src/mavlink/CMakeLists.txt, src/network/CMakeLists.txt, src/notification/CMakeLists.txt, src/sensor/CMakeLists.txt, src/settings/CMakeLists.txt, src/style/CMakeLists.txt, src/util/CMakeLists.txt, src/waterfall/CMakeLists.txt
- Uniform style
- Use "modern" cmake version 3.12
- Use new add_compile_definitions
- Add missing keywords
=> Improve our CMake system

CMakeLists.txt, cmake/git.cmake
=> CMakelists: Add and use git formula

src/sensor/ping.cpp
- Helps with different baudrates and more generic names
=> ping: Improve version regex

src/sensor/ping360.h
=> ping360: Add static constexpr to some variables

src/sensor/ping360.h
=> ping360: Only use heading when running in full scam mode

src/sensor/ping360.h
=> ping360: Add const for some functions

src/sensor/ping.cpp, src/sensor/pingsensor.cpp, src/sensor/pingsensor.h
This is important to know if the message was received and correct initialized
=> Use struct to handle group of messages

src/link/ping360simulationlink.cpp
=> ping360simulationlink: Add delay when not running in speed test mode

qml/Ping360Visualizer.qml, src/sensor/ping360.cpp, src/sensor/ping360.h
=> Ping360: Add checkbox for heading integration

src/link/link.cpp, src/link/link.h
=> link: Use a forward declaration for linkconfiguration

src/link/linkconfiguration.cpp, src/link/linkconfiguration.h
=> linkconfiguration: Add const in serialPort function

pingviewer.pro
=> pingviewer: Add more compiling checks

qml/main.qml
=> main: Check if the application is inside screen boundaries when started

examples/decode_sensor_binary_log.py
=> examples: First commit with decode_sensor_binary_log.py

.travis.yml, docs/logging-and-user-files.md, mkdocs.yml
pip2 is failing to install and run some packages
=> travis: Use python3

docs/mavlink-integration.md, mkdocs.yml
=> Add mavlink-integration docs

src/sensor/ping360.cpp, src/sensor/ping360.h
Add support to Ping360 async messages
- It only runs with our last test version 0.0.3
- We need to update the firmware check values to match our firmware release version
- We can do that after testing it with out last test firmware and approving this patch
=> Ping360 async

.appveyor.yml
=> appveyor: Update to use 64bits openssl 1.1

qml/DepthAxis.qml
=> DepthAxis: Remove debug message

README.md
=> README: Update badges to use github actions

src/main.cpp
=> main: Add OS information in GUI log

docs/firmware-update.md
=> docs: firmware-update: Add stm32flash output

examples/decode_sensor_binary_log.py
- Implemented `__iter__` method of `Log` class as a generator to efficiently read `.bin` files without needing to store the entire file in memory (reads and yields one message at a time).
- Implemented corresponding `parser` method which is a generator that decodes the messages.
- Updated `if __name__ == '__main__'` script component to use the more efficient syntax.
=> Process as generator; recover on error

.github/workflows/build.yml
Windows ecosystem is insane
---
Is there only crazinies in front of me
What I can see ?
Only windows in my way!
I can make it work now
but windows will break somehow.
I don't know what to say,
is only a normal windows day.
=> github: workflows: build: Fix windows deployment

.github/workflows/build.yml
=> github: workflows: build: Use different release action

qml/Ping360ControlPanel.qml, src/sensor/ping360.cpp, src/sensor/ping360.h
=> Fix ping360 reset advanced settings

docs/build-instructions.md
=> docs: build-instructions: Add steps to build documentation

src/flash/flasher.cpp
Needs to test under windows and mac
=> Fix flasher

src/CMakeLists.txt
Set program as a windows application
=> src: CMakeLists: Disable console on windows

src/CMakeLists.txt
=> src: CMakeLists: Fix usage of QuickCompiler with find_package for macOS

README.md
=> README: Update download links

docs/index.md
=> docs: Fix download url

src/waterfall/waterfallgradient.cpp
Fix #933
Not yet tested, but I believe that's all that should be required (it just wasn't enabled/matched in the regex).
=> Waterfall transparency fix

docs/display-settings.md
I wrote the original description based on an (incorrect) assumption about the setting while I didn't have access to a Ping360 for testing. 
Tried the setting the other day and it does something different, so this updated description reflects the actual behaviour.
=> docs: display-settings: fix head down description

src/sensor/ping360helperservice.cpp
The ping360 static ip address assignment was broken.
We were attempting to send the SetIP command directly to the sender. 
We need to broadcast the SetIP command on the same subnet where we received the Discovery response.
To test, assign a static ip to your computer's ethernet interface, then plug ping360 ethernet directly to your computer. Try to set your ping360 to a static ip address!
=> sensor/ping360helperservice: bugfix udp broadcast ip address assignemnt

CMakeLists.txt
=> cmake: Add Qt version

src/network/networkmanager.cpp
=> networkmanager: Add debug information subnet access

src/network/networkmanager.cpp
- Fix https://github.com/bluerobotics/ping-viewer/issues/1027
=> network: networkmanager: Add netmask check

.github/workflows/build.yml
=> github: Update action-zip user name

examples/decode_sensor_binary_log.py, examples/encode_sensor_binary_log.py
- Rename `Log` to `PingViewerLogReader`
- Add some convenience `Settings` classes (allows checking if settings have changed between pings)
- Create `PingViewerLogWriter` for encoding again (allows re-visualisation of processed results in Ping Viewer)
I've tested the encoding and it seems to work properly (the output can be viewed by PingViewer), although depending on how many/which messages are included, sometimes the output doesn't display.
=> Improve examples

src/link/filelink.cpp
=> src: link: filelink: Fix isWritable check

.github/workflows/build.yml, src/flash/flasher.cpp
Signed-off-by: Patrick Jo Pereira <patrickelectric@gmail.com>
=> src: flash: Move connections before start and add state check

src/sensor/pingparserext.cpp, src/sensor/sensor.cpp
=> Fix parser problem using latest version of ping-cpp 

.github/workflows/build.yml
=> github: workflows: build: Use ubuntu 18.04 to help with appimage compatibility

docs/device-settings-ping1d.md, docs/display-settings.md
- Update `v_sound` calculator link in Ping1D (#1041 only did it for Ping360 - didn't realise it was in both)
- (hopefully) fix some formatting of a numbered list
=> docs: minor fixes

qml/PingStatus.qml
=> qml: PingStatus: Fix sensorModel access

qml/FirmwareUpdate.qml
=> qml: FirmwareUpdate: Sort firmware by version

src/sensor/ping.cpp, src/sensor/ping.h
=> sensor: ping: Deal with dynamic profiles

src/sensor/ping360asciiprotocol.cpp, src/sensor/ping360asciiprotocol.h, src/sensor/ping360helperservice.cpp
fix #1054 
fix #1059
this might mean we're dropping support for ubunut 18.04? not sure. but we at least get a build. 18.04 was dropped from actions.
=> Fix link-local detection
